name: 'TravelNest Diagram Deploy'
description: 'Deploy a diagram to Structurizr'
inputs:
  architecture_file:
    description: 'File path for architecture'
    required: true
  aws_access_key_id:
    description: 'AWS Access key ID with permission to write to architecture s3 bucket'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret access key associated with above access key'
    required: true
outputs:
  result:
    description: "Result of the action"
runs:
  using: 'docker'
  image: 'Dockerfile'
