
name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - run: git fetch --all --prune
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install modules
      run: |
        npm ci
    - name: Run linting
      run: npm run lint
    - name: Run tests
      run: npm t
